import type { Equipment } from "./types";

/**
 * Phase 1 catalog: a local file, no database.
 *
 * SOURCING RULE — every row is `sourceType: "amazon"` with an ASIN, so the whole
 * plan drops into one Amazon cart with one click. Convenience is the product; a
 * plan split across five checkouts is just a shopping list. That rules out
 * direct-only brands (Rogue, REP Fitness, Force USA, Bells of Steel) however
 * good their gear is.
 *
 * `sourceType` / `sourceUrl` stay on the type so individual rows can be flipped
 * to a higher-paying brand program later without touching the planner. Amazon
 * pays 3% on Sports, Home, Home Improvement, Furniture and Tools — which is all
 * of this. Avoid ever adding Health & Personal Care or Grocery items
 * (supplements, protein): those pay 1%.
 *
 * Every ASIN here was verified by loading its listing and comparing the live
 * title against the row (see PROBLEM-PRODUCTS.md for what that caught). Image
 * ids and observed prices live in amazon-data.ts, deliberately separate.
 *
 * Prices remain OUR estimate, calibrated against an observed listing price and
 * labelled "est." in the UI — showing an Amazon price requires PA-API with a
 * timestamp under the Associates agreement.
 */

const amazon = (asin: string) => `https://www.amazon.com/dp/${asin}`;

/** Every item is Amazon-sourced in Phase 1; this keeps the rows terse. */
const az = (
  asin: string,
): Pick<Equipment, "sourceType" | "sourceUrl" | "asin"> => ({
  sourceType: "amazon",
  sourceUrl: amazon(asin),
  asin,
});

export const catalog: Equipment[] = [
  // ---------------------------------------------------------------- racks ---
  {
    id: "titan-t3-power-rack",
    name: 'T-3 Series Power Rack (24" depth)',
    brand: "Titan Fitness",
    category: "racks",
    widthIn: 47,
    depthIn: 36,
    heightIn: 82,
    clearanceIn: { front: 36, back: 6, left: 12, right: 12 },
    ceilingClearanceIn: 90,
    weightLbs: 216,
    estPriceUsd: 560,
    ...az("B0CQPCXJ3M"),
    tags: ["power rack", "squat", "pull-up", "cage", "best seller"],
  },
  {
    id: "titan-x3-flat-foot-rack",
    name: "X-3 Series Flat Foot Power Rack",
    brand: "Titan Fitness",
    category: "racks",
    widthIn: 49,
    depthIn: 53,
    heightIn: 91,
    clearanceIn: { front: 36, back: 6, left: 12, right: 12 },
    ceilingClearanceIn: 99,
    weightLbs: 300,
    estPriceUsd: 720,
    ...az("B09FVQTZZG"),
    tags: ["power rack", "no bolt", "flat foot", "pull-up", "heavy duty"],
  },
  {
    id: "hulkfit-power-cage",
    name: "1000 lb Capacity Power Cage",
    brand: "HulkFit",
    category: "racks",
    widthIn: 44,
    depthIn: 47,
    heightIn: 81,
    clearanceIn: { front: 36, back: 6, left: 12, right: 12 },
    ceilingClearanceIn: 89,
    weightLbs: 165,
    estPriceUsd: 416,
    ...az("B07R82448W"),
    tags: ["power cage", "budget", "squat", "pull-up"],
  },
  {
    id: "fitness-reality-810xlt",
    name: "810XLT Super Max Power Cage",
    brand: "Fitness Reality",
    category: "racks",
    widthIn: 47,
    depthIn: 48,
    heightIn: 83,
    clearanceIn: { front: 36, back: 6, left: 12, right: 12 },
    ceilingClearanceIn: 91,
    weightLbs: 106,
    estPriceUsd: 360,
    ...az("B07PVDCMJZ"),
    tags: ["power cage", "cheapest", "beginner", "squat"],
  },
  {
    id: "sportsroyals-cage-lat",
    name: "Power Cage with Lat Pulldown",
    brand: "Sportsroyals",
    category: "racks",
    widthIn: 68,
    depthIn: 49,
    heightIn: 83,
    clearanceIn: { front: 36, back: 12, left: 12, right: 12 },
    ceilingClearanceIn: 91,
    weightLbs: 180,
    estPriceUsd: 470,
    ...az("B0CZF39S2S"),
    tags: ["power cage", "lat pulldown", "all in one", "value"],
  },
  {
    id: "titan-folding-rack",
    name: "Wall-Mounted Folding Power Rack",
    brand: "Titan Fitness",
    category: "racks",
    widthIn: 50,
    depthIn: 22,
    heightIn: 91,
    clearanceIn: { front: 48, back: 0, left: 12, right: 12 },
    ceilingClearanceIn: 96,
    weightLbs: 100,
    estPriceUsd: 400,
    ...az("B09648F9GD"),
    tags: ["folding", "wall mount", "small space", "squat", "garage"],
  },
  {
    id: "titan-t2-squat-stand",
    name: "T-2 Series Squat Stand",
    brand: "Titan Fitness",
    category: "racks",
    widthIn: 48,
    depthIn: 46,
    heightIn: 84,
    clearanceIn: { front: 36, back: 12, left: 12, right: 12 },
    ceilingClearanceIn: 90,
    weightLbs: 90,
    estPriceUsd: 300,
    ...az("B00NAHQP90"),
    tags: ["squat stand", "compact", "pull-up", "small space"],
  },

  {
    id: "barwing-bench-press-rack",
    name: "Adjustable Bench Press Rack (1,250 lb)",
    brand: "BARWING",
    category: "racks",
    widthIn: 52,
    depthIn: 24,
    heightIn: 66,
    clearanceIn: { front: 36, back: 24, left: 18, right: 18 },
    weightLbs: 55,
    estPriceUsd: 130,
    ...az("B0F4WVQTYB"),
    tags: ["bench press", "squat stand", "uprights", "adjustable", "budget"],
  },
  {
    id: "yaheetech-bench-press-stand",
    name: "Adjustable Squat & Bench Press Stands (pair)",
    brand: "Yaheetech",
    category: "racks",
    widthIn: 48,
    depthIn: 20,
    heightIn: 66,
    clearanceIn: { front: 36, back: 24, left: 18, right: 18 },
    weightLbs: 40,
    estPriceUsd: 75,
    ...az("B01855EGXI"),
    tags: ["bench press", "squat stand", "uprights", "cheapest"],
  },

  // ------------------------------------------------------------- barbells ---
  {
    id: "cap-olympic-bar-7ft",
    name: "The Beast 7 ft Olympic Bar (1,200 lb)",
    brand: "CAP Barbell",
    category: "barbells",
    widthIn: 86,
    depthIn: 3,
    heightIn: 3,
    weightLbs: 45,
    estPriceUsd: 180,
    ...az("B0B35ZF8XC"),
    tags: ["barbell", "olympic", "value", "best seller"],
  },
  {
    id: "synergee-games-bar",
    name: "Games Barbell 15 kg (women's)",
    brand: "Synergee",
    category: "barbells",
    widthIn: 79,
    depthIn: 3,
    heightIn: 3,
    weightLbs: 33,
    estPriceUsd: 150,
    ...az("B0CTRNZ9XC"),
    tags: ["barbell", "olympic", "multipurpose", "knurling"],
  },
  {
    id: "titan-olympic-bar",
    name: "Olympic Barbell (1500 lb rated)",
    brand: "Titan Fitness",
    category: "barbells",
    widthIn: 86,
    depthIn: 3,
    heightIn: 3,
    weightLbs: 45,
    estPriceUsd: 200,
    ...az("B0C8BS6L3D"),
    tags: ["barbell", "olympic", "power bar", "stiff"],
  },
  {
    id: "papababe-ez-curl-bar",
    name: "Olympic EZ Curl Bar",
    brand: "CAP Barbell",
    category: "barbells",
    widthIn: 47,
    depthIn: 3,
    heightIn: 3,
    weightLbs: 18,
    estPriceUsd: 38,
    ...az("B0BFBVZ8M7"),
    tags: ["curl bar", "arms", "accessory bar"],
  },
  {
    id: "cap-trap-bar",
    name: "Olympic Hex Trap Bar",
    brand: "CAP Barbell",
    category: "barbells",
    widthIn: 56,
    depthIn: 24,
    heightIn: 5,
    clearanceIn: { front: 12, back: 12, left: 12, right: 12 },
    weightLbs: 52,
    estPriceUsd: 200,
    ...az("B083R4RMTH"),
    tags: ["trap bar", "hex bar", "deadlift"],
  },
  {
    id: "titan-safety-squat-bar",
    name: "Safety Squat Bar",
    brand: "Titan Fitness",
    category: "barbells",
    widthIn: 86,
    depthIn: 14,
    heightIn: 11,
    weightLbs: 70,
    estPriceUsd: 330,
    ...az("B09D12QXYM"),
    tags: ["specialty bar", "squat", "ssb", "shoulder friendly"],
  },

  // --------------------------------------------------------------- plates ---
  {
    id: "signature-bumper-set-260",
    name: "Olympic Bumper Plate Set — 260 lb",
    brand: "Fitvids",
    category: "plates",
    widthIn: 18,
    depthIn: 18,
    heightIn: 16,
    weightLbs: 260,
    estPriceUsd: 500,
    ...az("B0CHLNLJF3"),
    tags: ["bumper plates", "olympic", "set", "best seller"],
  },
  {
    id: "yes4all-bumper-set-160",
    name: "Olympic Bumper Plate Set — 210 lb",
    brand: "Signature Fitness",
    category: "plates",
    widthIn: 18,
    depthIn: 18,
    heightIn: 11,
    weightLbs: 210,
    estPriceUsd: 420,
    ...az("B0BZWY8Z2D"),
    tags: ["bumper plates", "starter", "set"],
  },
  {
    id: "cap-cast-iron-set-300",
    name: "Cast Iron Olympic Plate Set — 300 lb",
    brand: "CAP Barbell",
    category: "plates",
    widthIn: 18,
    depthIn: 18,
    heightIn: 13,
    weightLbs: 300,
    estPriceUsd: 450,
    ...az("B002OP0DLA"),
    tags: ["iron plates", "cheapest per lb", "set"],
  },
  {
    id: "titan-change-plate-set",
    name: "Fractional Change Plate Set — 25 lb",
    brand: "Titan Fitness",
    category: "plates",
    widthIn: 10,
    depthIn: 10,
    heightIn: 8,
    weightLbs: 37.5,
    estPriceUsd: 130,
    ...az("B07MLBS57X"),
    tags: ["change plates", "fractional", "microloading"],
  },

  // ------------------------------------------------------------ dumbbells ---
  {
    id: "bowflex-selecttech-552",
    name: "SelectTech 552 Adjustable Dumbbell (single)",
    brand: "Bowflex",
    category: "dumbbells",
    widthIn: 17,
    depthIn: 10,
    heightIn: 10,
    clearanceIn: { front: 24 },
    weightLbs: 52.5,
    estPriceUsd: 250,
    ...az("B0G6Z84TQM"),
    tags: ["adjustable", "dial", "pair", "best seller", "space saving"],
  },
  {
    id: "powerblock-elite-exp-50",
    name: "Elite EXP Adjustable Dumbbells (5–50 lb pair)",
    brand: "PowerBlock",
    category: "dumbbells",
    widthIn: 16,
    depthIn: 10,
    heightIn: 12,
    clearanceIn: { front: 24 },
    weightLbs: 100,
    estPriceUsd: 399,
    ...az("B00A21NRNO"),
    tags: ["adjustable", "space saving", "pair", "expandable"],
  },
  {
    id: "nuobell-adjustable-80",
    name: "Adjustable Dumbbells 80 lb (pair)",
    brand: "Nüobell",
    category: "dumbbells",
    widthIn: 20,
    depthIn: 10,
    heightIn: 10,
    clearanceIn: { front: 24 },
    weightLbs: 160,
    estPriceUsd: 750,
    ...az("B0CM9VR4CL"),
    tags: ["adjustable", "premium", "pair", "fast change"],
  },
  {
    id: "yes4all-adjustable-105",
    name: "Adjustable Dumbbell Set — 105 lb total",
    brand: "Yes4All",
    category: "dumbbells",
    widthIn: 20,
    depthIn: 10,
    heightIn: 10,
    clearanceIn: { front: 24 },
    weightLbs: 105,
    estPriceUsd: 120,
    ...az("B07YYWBGNJ"),
    tags: ["adjustable", "spinlock", "budget", "pair"],
  },
  {
    id: "cap-hex-pair-40",
    name: "Rubber Coated Dumbbell — 40 lb",
    brand: "CAP Barbell",
    category: "dumbbells",
    widthIn: 14,
    depthIn: 9,
    heightIn: 9,
    weightLbs: 40,
    estPriceUsd: 39,
    ...az("B093QYT1DW"),
    tags: ["hex", "single pair", "fixed weight"],
  },

  {
    id: "hex-dumbbell-set-5-50-rack",
    name: "Rubber Hex Dumbbell Set 5–50 lb with Rack",
    brand: "Signature Fitness",
    category: "dumbbells",
    widthIn: 72,
    depthIn: 26,
    heightIn: 32,
    clearanceIn: { front: 36 },
    weightLbs: 650,
    estPriceUsd: 730,
    ...az("B0FL2BF3DQ"),
    tags: ["hex", "full set", "with rack", "5-50", "heavy"],
  },
  {
    id: "hex-dumbbell-set-550-rack",
    name: "Rubber Hex Dumbbell Set 550 lb with Rack",
    brand: "Signature Fitness",
    category: "dumbbells",
    widthIn: 78,
    depthIn: 28,
    heightIn: 34,
    clearanceIn: { front: 36 },
    weightLbs: 700,
    estPriceUsd: 529,
    ...az("B0G19C4BNG"),
    tags: ["hex", "full set", "with rack", "10-60", "heavy"],
  },
  {
    id: "signature-hex-pair-50",
    name: "Rubber Coated Hex Dumbbell Pair — 50 lb",
    brand: "Signature Fitness",
    category: "dumbbells",
    widthIn: 16,
    depthIn: 10,
    heightIn: 10,
    weightLbs: 100,
    estPriceUsd: 120,
    ...az("B0CYFCC81C"),
    tags: ["hex", "single pair", "fixed weight", "heavy"],
  },
  {
    id: "hulkfit-hex-pair-heavy",
    name: "Rubber Coated Hex Dumbbell Pair — 70 lb",
    brand: "HulkFit",
    category: "dumbbells",
    widthIn: 18,
    depthIn: 11,
    heightIn: 11,
    weightLbs: 140,
    estPriceUsd: 113,
    ...az("B0H4G9GHDQ"),
    tags: ["hex", "single pair", "fixed weight", "anti-roll"],
  },
  {
    id: "handbode-hex-pair-100",
    name: "Rubber Encased Hex Dumbbell Pair — 100 lb",
    brand: "HANDBODE",
    category: "dumbbells",
    widthIn: 20,
    depthIn: 12,
    heightIn: 12,
    weightLbs: 200,
    estPriceUsd: 95,
    ...az("B0H2DK6Q6P"),
    tags: ["hex", "single pair", "fixed weight", "heaviest"],
  },

  // -------------------------------------------------------------- benches ---
  {
    id: "flybird-adjustable-bench",
    name: "Adjustable Weight Bench (foldable)",
    brand: "FLYBIRD",
    category: "benches",
    widthIn: 24,
    depthIn: 49,
    heightIn: 18,
    clearanceIn: { front: 24, back: 24, left: 24, right: 24 },
    weightLbs: 40,
    estPriceUsd: 150,
    ...az("B07DNYSJ8W"),
    tags: ["adjustable", "folding", "small space", "best seller"],
  },
  {
    id: "finer-form-fid-bench",
    name: "Multi-Functional FID Bench",
    brand: "Finer Form",
    category: "benches",
    widthIn: 24,
    depthIn: 52,
    heightIn: 19,
    clearanceIn: { front: 24, back: 24, left: 24, right: 24 },
    weightLbs: 62,
    estPriceUsd: 250,
    ...az("B08YWHN79N"),
    tags: ["adjustable", "incline", "decline", "fid", "leg hold"],
  },
  {
    id: "fitness-reality-1000-bench",
    name: "2000 Super Max XL Adjustable Bench",
    brand: "Fitness Reality",
    category: "benches",
    widthIn: 25,
    depthIn: 51,
    heightIn: 19,
    clearanceIn: { front: 24, back: 24 },
    weightLbs: 55,
    estPriceUsd: 200,
    ...az("B07B3Q9F22"),
    tags: ["adjustable", "budget", "incline"],
  },
  {
    id: "titan-flat-bench",
    name: "TITAN Series Single Post Flat Bench",
    brand: "Titan Fitness",
    category: "benches",
    widthIn: 24,
    depthIn: 48,
    heightIn: 17,
    clearanceIn: { front: 24, back: 24, left: 24, right: 24 },
    weightLbs: 55,
    estPriceUsd: 276,
    ...az("B07H519KMQ"),
    tags: ["flat bench", "bench press", "stable"],
  },
  {
    id: "marcy-preacher-curl-bench",
    name: "6-Position Utility Bench with Leg Developer",
    brand: "Marcy",
    category: "benches",
    widthIn: 26,
    depthIn: 56,
    heightIn: 40,
    clearanceIn: { front: 24, back: 18 },
    weightLbs: 45,
    estPriceUsd: 170,
    ...az("B00FJ2PL26"),
    tags: ["preacher", "arms", "isolation"],
  },

  // ------------------------------------------------------------- machines ---
  {
    id: "marcy-smith-cage-sm4008",
    name: "SM-4008 Smith Machine Cage System",
    brand: "Marcy",
    category: "machines",
    widthIn: 50,
    depthIn: 79,
    heightIn: 86,
    clearanceIn: { front: 36, back: 6, left: 18, right: 18 },
    ceilingClearanceIn: 92,
    weightLbs: 400,
    estPriceUsd: 2000,
    ...az("B0H475H6JH"),
    tags: ["smith machine", "all in one", "guided", "cable"],
  },
  {
    id: "valor-bd-62-functional-trainer",
    name: "BD-62 Cable Crossover Functional Trainer",
    brand: "Valor Fitness",
    category: "machines",
    widthIn: 55,
    depthIn: 48,
    heightIn: 84,
    clearanceIn: { front: 48, back: 6, left: 24, right: 24 },
    ceilingClearanceIn: 90,
    weightLbs: 400,
    estPriceUsd: 879,
    ...az("B07ZWGQ9WM"),
    tags: ["functional trainer", "cable", "dual stack", "crossover"],
  },
  {
    id: "valor-cb-12-lat-pulldown",
    name: "CB-12 Lat Pulldown / Low Row",
    brand: "Valor Fitness",
    category: "machines",
    widthIn: 47,
    depthIn: 53,
    heightIn: 84,
    clearanceIn: { front: 36, back: 12 },
    ceilingClearanceIn: 90,
    weightLbs: 220,
    estPriceUsd: 389,
    ...az("B0FHQL4MPR"),
    tags: ["lat pulldown", "low row", "back"],
  },
  {
    id: "powerline-leg-press",
    name: "GLPH1100 Leg Press / Hack Squat",
    brand: "Body-Solid",
    category: "machines",
    widthIn: 43,
    depthIn: 89,
    heightIn: 60,
    clearanceIn: { front: 24, back: 24, left: 18, right: 18 },
    weightLbs: 260,
    estPriceUsd: 1735,
    ...az("B0028O9ADE"),
    tags: ["leg press", "hack squat", "legs", "heavy"],
  },
  {
    id: "titan-belt-squat",
    name: "Belt Squat Machine",
    brand: "Titan Fitness",
    category: "machines",
    widthIn: 48,
    depthIn: 60,
    heightIn: 48,
    clearanceIn: { front: 24, back: 24 },
    weightLbs: 300,
    estPriceUsd: 1150,
    ...az("B0DFKMGKFV"),
    tags: ["belt squat", "legs", "low back friendly"],
  },
  {
    id: "titan-cable-tower",
    name: "T-2 Series LAT Pulldown & Low Row",
    brand: "Titan Fitness",
    category: "machines",
    widthIn: 48,
    depthIn: 40,
    heightIn: 71,
    clearanceIn: { front: 48, back: 4 },
    ceilingClearanceIn: 90,
    weightLbs: 180,
    estPriceUsd: 325,
    ...az("B09WGGBZT8"),
    tags: ["cable", "pulley", "compact", "single stack"],
  },
  {
    id: "titan-ghd",
    name: "Glute Ham Developer (GHD)",
    brand: "Titan Fitness",
    category: "machines",
    widthIn: 30,
    depthIn: 62,
    heightIn: 50,
    clearanceIn: { front: 24, back: 24 },
    weightLbs: 150,
    estPriceUsd: 627,
    ...az("B01N3UGETO"),
    tags: ["ghd", "posterior chain", "core"],
  },
  {
    id: "marcy-mwm-988-home-gym",
    name: "MWM-988 150 lb Stack Home Gym",
    brand: "Marcy",
    category: "machines",
    widthIn: 68,
    depthIn: 36,
    heightIn: 79,
    clearanceIn: { front: 24, back: 12, left: 18, right: 18 },
    ceilingClearanceIn: 85,
    weightLbs: 250,
    estPriceUsd: 500,
    ...az("B0090OKEB2"),
    tags: ["home gym", "weight stack", "multi station", "beginner"],
  },

  // --------------------------------------------------------------- cardio ---
  {
    id: "concept2-rowerg",
    name: "RowErg Rowing Machine",
    brand: "Concept2",
    category: "cardio",
    widthIn: 24,
    depthIn: 96,
    heightIn: 20,
    clearanceIn: { front: 24, back: 12, left: 12, right: 12 },
    weightLbs: 57,
    estPriceUsd: 990,
    ...az("B00NH9WEUA"),
    tags: ["rower", "conditioning", "gold standard", "splits apart"],
  },
  {
    id: "assault-airbike-classic",
    name: "AssaultBike Classic",
    brand: "Titan Fitness",
    category: "cardio",
    widthIn: 24,
    depthIn: 51,
    heightIn: 53,
    clearanceIn: { front: 18, back: 18, left: 12, right: 12 },
    weightLbs: 98,
    estPriceUsd: 750,
    ...az("B093HKN7TW"),
    tags: ["air bike", "conditioning", "hiit", "brutal"],
  },
  {
    id: "schwinn-ic4-bike",
    name: "IC Series Indoor Cycling Bike",
    brand: "Schwinn",
    category: "cardio",
    widthIn: 21,
    depthIn: 48,
    heightIn: 51,
    clearanceIn: { left: 12, right: 12 },
    weightLbs: 106,
    estPriceUsd: 795,
    ...az("B07WZXSDKW"),
    tags: ["spin bike", "cycling", "low impact", "app connected"],
  },
  {
    id: "nordictrack-t-series-treadmill",
    name: "T Series Folding Treadmill",
    brand: "NordicTrack",
    category: "cardio",
    widthIn: 36,
    depthIn: 71,
    heightIn: 60,
    clearanceIn: { back: 36, left: 12, right: 12 },
    weightLbs: 250,
    estPriceUsd: 999,
    ...az("B0D7XGWMRD"),
    tags: ["treadmill", "folding", "running", "incline"],
  },
  {
    id: "sunny-sf-b1805-bike",
    name: "Magnetic Exercise Bike (44 lb flywheel)",
    brand: "Sunny Health & Fitness",
    category: "cardio",
    widthIn: 22,
    depthIn: 48,
    heightIn: 47,
    clearanceIn: { left: 12, right: 12 },
    weightLbs: 130,
    estPriceUsd: 700,
    ...az("B09R5QRVWG"),
    tags: ["spin bike", "budget", "quiet", "cycling"],
  },
  {
    id: "sunny-sf-rw5515-rower",
    name: "Smart Magnetic Rowing Machine (extra-long rail)",
    brand: "Sunny Health & Fitness",
    category: "cardio",
    widthIn: 22,
    depthIn: 82,
    heightIn: 23,
    clearanceIn: { front: 24, back: 12, left: 12, right: 12 },
    weightLbs: 60,
    estPriceUsd: 330,
    ...az("B09Y9H42CH"),
    tags: ["rower", "budget", "quiet", "folds up"],
  },

  {
    id: "merach-t12-treadmill",
    name: "T12 Foldable Treadmill (300 lb capacity)",
    brand: "MERACH",
    category: "cardio",
    widthIn: 30,
    depthIn: 62,
    heightIn: 50,
    clearanceIn: { back: 36, left: 12, right: 12 },
    weightLbs: 130,
    estPriceUsd: 360,
    ...az("B0F1L2BF59"),
    tags: ["treadmill", "folding", "running", "mid range"],
  },
  {
    id: "sunny-auto-incline-treadmill",
    name: "Smart Wi-Fi Treadmill with Auto Incline",
    brand: "Sunny Health & Fitness",
    category: "cardio",
    widthIn: 33,
    depthIn: 70,
    heightIn: 57,
    clearanceIn: { back: 36, left: 12, right: 12 },
    weightLbs: 200,
    estPriceUsd: 1100,
    ...az("B0DMGTW62D"),
    tags: ["treadmill", "auto incline", "smart", "premium"],
  },
  {
    id: "evitrend-incline-treadmill",
    name: "18% Incline Folding Treadmill (350 lb capacity)",
    brand: "EviTrend",
    category: "cardio",
    widthIn: 27,
    depthIn: 55,
    heightIn: 45,
    clearanceIn: { back: 30, left: 12, right: 12 },
    weightLbs: 90,
    estPriceUsd: 140,
    ...az("B0HF7TM17Q"),
    tags: ["treadmill", "folding", "incline", "budget", "walking"],
  },

  // ------------------------------------------------------------- flooring ---
  {
    id: "rubber-cal-stall-mat-4x6",
    name: 'Rubber Stall Mat 4 ft × 6 ft (3/4")',
    brand: "DWC",
    category: "flooring",
    widthIn: 48,
    depthIn: 72,
    heightIn: 0.75,
    weightLbs: 95,
    estPriceUsd: 166,
    ...az("B00I0DLVV6"),
    tags: ["stall mat", "rubber", "deadlift proof", "24 sq ft"],
  },
  {
    id: "incstores-rubber-tile-24",
    name: 'Interlocking Rubber Tile 24" × 24" (3/8")',
    brand: "AIRHOP",
    category: "flooring",
    widthIn: 96,
    depthIn: 72,
    heightIn: 0.56,
    weightLbs: 60,
    estPriceUsd: 100,
    ...az("B0CNG8MDWB"),
    tags: ["tile", "rubber", "interlocking", "4 sq ft"],
  },
  {
    id: "prosourcefit-rolled-rubber",
    name: 'Rolled Rubber Flooring 4 ft × 10 ft (1/4")',
    brand: "Flooring Inc",
    category: "flooring",
    widthIn: 48,
    depthIn: 120,
    heightIn: 0.25,
    weightLbs: 80,
    estPriceUsd: 135,
    ...az("B09TRPYFVT"),
    tags: ["rolled rubber", "seamless", "40 sq ft"],
  },
  {
    id: "gorilla-mats-4x6",
    name: "Premium Large Exercise Mat 4 ft × 6 ft",
    brand: "Gorilla Mats",
    category: "flooring",
    widthIn: 48,
    depthIn: 72,
    heightIn: 0.3,
    weightLbs: 20,
    estPriceUsd: 160,
    ...az("B06XXPQZBP"),
    tags: ["mat", "bodyweight", "yoga", "non slip", "24 sq ft"],
  },
  {
    id: "balancefrom-foam-tile-24",
    name: 'EVA Foam Tile 24" × 24" (1/2")',
    brand: "ProsourceFit",
    category: "flooring",
    widthIn: 48,
    depthIn: 72,
    heightIn: 0.5,
    weightLbs: 12,
    estPriceUsd: 50,
    ...az("B07YN1W5W3"),
    tags: ["foam", "cheapest", "light use", "4 sq ft"],
  },

  // -------------------------------------------------------------- storage ---
  {
    id: "yes4all-plate-tree",
    name: "Plate Tree with 4 Barbell Holders",
    brand: "Yes4All",
    category: "storage",
    widthIn: 24,
    depthIn: 24,
    heightIn: 48,
    clearanceIn: { front: 24 },
    weightLbs: 45,
    estPriceUsd: 109,
    ...az("B0B391B9PY"),
    tags: ["plate storage", "tree", "organization"],
  },
  {
    id: "titan-dumbbell-rack-3tier",
    name: "2/3-Tier Dumbbell Rack",
    brand: "CAP Barbell",
    category: "storage",
    widthIn: 72,
    depthIn: 25,
    heightIn: 31,
    clearanceIn: { front: 30 },
    weightLbs: 130,
    estPriceUsd: 140,
    ...az("B00ZEYSVDU"),
    tags: ["dumbbell rack", "storage", "3 tier"],
  },
  {
    id: "synergee-vertical-bar-holder",
    name: "9-Barbell Vertical Rack",
    brand: "REP Fitness",
    category: "storage",
    widthIn: 24,
    depthIn: 24,
    heightIn: 36,
    clearanceIn: { front: 18 },
    weightLbs: 55,
    estPriceUsd: 150,
    ...az("B017WQURWU"),
    tags: ["barbell storage", "vertical", "space saving"],
  },
  {
    id: "titan-wall-bar-holder",
    name: "Wall-Mounted Horizontal Bar Holder",
    brand: "Luwint",
    category: "storage",
    widthIn: 30,
    depthIn: 10,
    heightIn: 8,
    weightLbs: 15,
    estPriceUsd: 40,
    ...az("B0B5Q681MB"),
    tags: ["wall mount", "barbell storage", "small space"],
  },
  {
    id: "amazon-basics-shelving",
    name: 'Heavy Duty Storage Shelving 72" × 24" × 72"',
    brand: "Amazon Basics",
    category: "storage",
    widthIn: 72,
    depthIn: 24,
    heightIn: 72,
    clearanceIn: { front: 30 },
    weightLbs: 120,
    estPriceUsd: 228,
    ...az("B072MF4SHR"),
    tags: ["shelving", "storage", "organization", "wire rack"],
  },

  // ---------------------------------------------------------- accessories ---
  {
    id: "yes4all-dip-attachment",
    name: "Dip Bar Attachment for Squat Rack",
    brand: "A2ZCARE",
    category: "accessories",
    widthIn: 24,
    depthIn: 24,
    heightIn: 10,
    clearanceIn: { front: 24 },
    weightLbs: 25,
    estPriceUsd: 55,
    ...az("B09XV3KNHW"),
    tags: ["dip", "rack attachment", "bodyweight", "triceps"],
  },
  {
    id: "titan-plyo-box-3in1",
    name: '3-in-1 Soft Plyo Box (20/24/30")',
    brand: "BalanceFrom",
    category: "accessories",
    widthIn: 30,
    depthIn: 24,
    heightIn: 20,
    clearanceIn: { front: 36 },
    weightLbs: 45,
    estPriceUsd: 113,
    ...az("B0BZQXKHZ3"),
    tags: ["plyo box", "jumps", "step ups", "soft"],
  },
  {
    id: "yes4all-kettlebell-set",
    name: "Premier Kettlebell Set with Rack",
    brand: "Ader",
    category: "accessories",
    widthIn: 30,
    depthIn: 16,
    heightIn: 24,
    clearanceIn: { front: 24 },
    weightLbs: 150,
    estPriceUsd: 560,
    ...az("B001MQCW34"),
    tags: ["kettlebell", "swings", "set", "conditioning"],
  },
  {
    id: "serious-steel-band-set",
    name: "Resistance Band Set (5 bands)",
    brand: "LEEKEY",
    category: "accessories",
    widthIn: 12,
    depthIn: 8,
    heightIn: 6,
    weightLbs: 5,
    estPriceUsd: 20,
    ...az("B07DR9BT5G"),
    tags: ["bands", "accommodating resistance", "mobility", "assisted pull-up"],
  },
  {
    id: "gym-mirror-48x72",
    name: 'Wall Mirror 48" × 72"',
    brand: "Fab Glass and Mirror",
    category: "accessories",
    widthIn: 72,
    depthIn: 2,
    heightIn: 48,
    weightLbs: 60,
    estPriceUsd: 466,
    ...az("B0924SPDXG"),
    tags: ["mirror", "form check", "wall", "makes room look bigger"],
  },
  {
    id: "vornado-air-circulator",
    name: 'Model 80 High-Velocity Box Fan (20")',
    brand: "Vornado",
    category: "accessories",
    widthIn: 20,
    depthIn: 10,
    heightIn: 22,
    weightLbs: 15,
    estPriceUsd: 80,
    ...az("B0DQLWLQDS"),
    tags: ["fan", "airflow", "garage gym", "cooling"],
  },
];

const byId = new Map(catalog.map((item) => [item.id, item]));

export function getEquipment(id: string): Equipment | undefined {
  return byId.get(id);
}

/** Throws for unknown ids — use where the id is known to come from the catalog. */
export function requireEquipment(id: string): Equipment {
  const item = byId.get(id);
  if (!item) throw new Error(`Unknown equipment id: ${id}`);
  return item;
}
